apps_src += $(addprefix apps/calcboy/emu/,\
audio.c                 \
cpu.c                   \
debugger-dummy.c        \
disassembler.c          \
emu.c                   \
fileio.c                \
lcd.c                   \
main.c                  \
mmu.c                   \
sdl.c                   \
state.c                 \
)